### ISSUE TITLE
Changing between different wallets switches to overview tab

### ISSUE THREAD

**Issue by Tracachang** [bitcoinknots/bitcoin#83] opened 2024-06-09 11:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When using multiple wallets (switching them) If you do this in the Transactions tab, instead of displaying the transactions of the selected wallet it will switch to the Overview tab. 

It only happens in the Transactions tab, the other tabs (Overview, Send or Receive) work as expected.

### Expected behaviour

It should display the transactions of the selected wallet instead of switching to overview.

### Steps to reproduce

Go to the Transactions tab and select a different wallet.

### How did you obtain Bitcoin Knots

Pre-built binaries

### What version of Bitcoin Knots are you using?

Bitcoin Knots version v26.1.knots20240513

### Operating system and version

Fedora Workstation 40 (gnome)

**Comment by luke-jr** [comment] 2024-06-10 13:53
Confirmed. Bug was introduced by https://github.com/bitcoin-core/gui/pull/815, and will be resolved in next version

**Comment by luke-jr** [comment] 2024-06-23 14:54
Please confirm this is fixed in 27.1.knots20260621 and close if so

**Closed as completed** 2024-06-23 20:43 UTC
Labels: bug

**Comment by Tracachang** [comment] 2024-06-23 20:44
I confirm, fixed

**Comment by pablomartin4btc** [comment] 2024-07-30 16:44
> <h3>Steps to reproduce</h3>

> Go to the Transactions tab and select a different wallet.

@Tracachang, just to be clear, you meant: selecting a different wallet by "Open Wallet" menu action? Switching among wallets from the wallets (already loaded) combo box (at the top right section of the main window), won't produce such change in the behaviour. Thanks!

**Comment by Tracachang** [comment] 2024-07-31 20:41
> > ### Steps to reproduce
> 
> > Go to the Transactions tab and select a different wallet.
> 
> @Tracachang, just to be clear, you meant: selecting a different wallet by "Open Wallet" menu action? Switching among wallets from the wallets (already loaded) combo box (at the top right section of the main window), won't produce such change in the behaviour. Thanks!

yes, switching among wallets from the wallets (already loaded) combo box (at the top right section of the main window)

**Comment by pablomartin4btc** [comment] 2024-08-01 12:25
> yes, switching among wallets from the wallets (already loaded) combo box (at the top right section of the main window)

Mmm... the line that was causing that behaviour of switching from transactions to overview tab is this one:

`
        if (historyAction->isChecked()) gotoOverviewPage();
`

<details>
<summary>That's inside the function <code>void BitcoinGUI::enableHistoryAction(bool privacy)</code> which was referenced/ called from 2 places... when the user ticks the "mask values" from the Settings menu (pls click here to watch animated gif).</summary>

![mask values - switch from transaction tab to overview tab](https://github.com/user-attachments/assets/f7e1d02a-f753-4396-9d04-e3712179b75b)

</details>

The idea (introduced in [#708](https://github.com/bitcoin-core/gui/pull/708#issuecomment-1449025828)) was to move from the transaction tab to the overview tab since it was going to be disabled anyways.


<details>
<summary>The 2nd place where this function was called was in <code>addWallet</code> (still is in <code>bitcoin-qt</code> but bitcoin-core/gui/pull/815 is removing it), which is called when a new wallet is created or opened/ loaded, and here we can see the undesired secondary effect you were mentioning on this issue (pls click here to watch animated gif).</summary>

![switch from transaction tab to overview tab when opening wallets](https://github.com/user-attachments/assets/6bdc075e-5b12-4f78-8d8d-32d16a14af99)

</details>

Switching among loaded wallets from the combo box doesn't switch between tabs (this is still in `bitcoin-qt`, unless there's something in `bitcoinknots` that causes it and I'm not aware of:

![switch wallets from combo dont switch from transaction tab to overview tab](https://github.com/user-attachments/assets/ec729f2f-4d74-4b54-af01-1b2150ac2d37)
